(add-pvar-name "A" "B" "C" (make-arity))
(add-pvar-name "P" (make-arity (py "alpha")))
(add-var-name "x" (py "alpha"))

(set-goal (pf "(A -> (ex x P x)) -> (ex x (A -> P x))"))
(assume "u")
(use "Stab")
(assume "v")
(use "v")
(ex-intro "x")
(assume "a")
(use "Stab")
(assume "np")
(use "v")
(search)
(cdp)

(set-goal (pf "((A -> B) -> C) -> (A -> C) -> C"))
(assume "u")
(use "Stab")
(assume "v")
(use "v")
(assume "w")
(use "u")
(assume "a")
(use "Stab")
(assume "nb")
(use "v")
(assume "ac")
(use "w")
(use "a")
(cdp)

(set-goal (pf "(A -> B) ord (B -> A)"))
(use "Stab")
(assume "u")
(use "u")
(intro 0)
(assume "a")
(use "Stab")
(assume "nb")
(use "u")
(intro 1)
(assume "b")
(use "a")
(cdp)

(set-goal (pf "A -> (ex x (P x)) -> ex x (A -> (P x))")
(assume "a")
(assume "v")
(ex-elim "v")
(assume "x")
(assume "px")
(ex-intro (pt "x"))
(assume "a1")
(use "px")
(cdp)

(set-goal (pf "((A -> B) -> A) -> A"))
(assume "u")
(use "Stab")
(assume "na")
(use "na")
(use "u")
(assume "a")
(use "Stab")
(assume "nb")
(use "na")
(use "a")
(cdp)
